import client from "./client";

export const getDashboard = () => client.get("/admin/dashboard");
export const getPendingReviews = () => client.get("/admin/reviews");
export const getPendingProjectReviews = () => client.get("/admin/project-reviews");
export const reviewArticle = (id, payload) => client.post(`/admin/articles/${id}/review`, payload);
export const reviewProject = (id, payload) => client.post(`/admin/projects/${id}/review`, payload);
export const getUsers = (params = {}) => client.get("/admin/users", { params });
export const updateUserRole = (id, payload) => client.put(`/admin/users/${id}/role`, payload);
export const updateUserStatus = (id, payload) => client.put(`/admin/users/${id}/status`, payload);
export const getAdminArticles = (params = {}) => client.get("/admin/articles", { params });
export const getAdminArticleDetail = (id) => client.get(`/admin/articles/${id}`);
export const updateAdminArticleTaxonomy = (id, payload) => client.put(`/admin/articles/${id}/taxonomy`, payload);
export const bulkUpdateAdminArticleTaxonomy = (payload) => client.put("/admin/articles/taxonomy/bulk", payload);
export const bulkPublishAdminArticles = (payload) => client.post("/admin/articles/publish/bulk", payload);
export const bulkDeleteAdminArticles = (payload) => client.post("/admin/articles/delete/bulk", payload);
export const bulkRejectAdminArticles = (payload) => client.post("/admin/articles/reject/bulk", payload);
export const bulkApproveAdminArticles = (payload) => client.post("/admin/articles/approve/bulk", payload);
export const publishAdminArticle = (id) => client.post(`/admin/articles/${id}/publish`);
export const deleteAdminArticle = (id) => client.delete(`/admin/articles/${id}`);
export const getAdminProjects = (params = {}) => client.get("/admin/projects", { params });
export const getAdminProjectDetail = (id) => client.get(`/admin/projects/${id}`);
export const bulkReviewAdminProjects = (payload) => client.post("/admin/projects/review/bulk", payload);
export const publishAdminProject = (id) => client.post(`/admin/projects/${id}/publish`);
export const updateAdminProjectMeta = (id, payload) => client.put(`/admin/projects/${id}/meta`, payload);
export const deleteAdminProject = (id) => client.delete(`/admin/projects/${id}`);
export const getAdminComments = (params = {}) => client.get("/admin/comments", { params });
export const deleteAdminComment = (id) => client.delete(`/admin/comments/${id}`);
export const getAdminLogs = (params = {}) => client.get("/admin/logs", { params });
export const getModerationHits = (params = {}) => client.get("/admin/moderation-hits", { params });
export const getModerationSettings = () => client.get("/admin/moderation-settings");
export const updateModerationSettings = (payload) => client.put("/admin/moderation-settings", payload);
export const getSensitiveWords = (params = {}) => client.get("/admin/sensitive-words", { params });
export const createSensitiveWord = (payload) => client.post("/admin/sensitive-words", payload);
export const deleteSensitiveWord = (id) => client.delete(`/admin/sensitive-words/${id}`);
export const getAdminUploads = () => client.get("/admin/uploads");
export const deleteAdminUpload = (name) => client.delete(`/admin/uploads/${encodeURIComponent(name)}`);
export const getAIReviewContent = (type, id) => client.get(`/admin/ai-review/${type}/${id}/content`);
export const getAIReviewResult = (type, id) => client.get(`/admin/ai-review/${type}/${id}`);
export const saveAIReviewResult = (type, id, payload) => client.post(`/admin/ai-review/${type}/${id}`, payload);
