package service

import "errors"

var (
	ErrUserBanned           = errors.New("已被封禁的用户不能创建文章")
	ErrArticleNoPermission  = errors.New("没有权限操作该文章")
	ErrProjectNotPublished  = errors.New("项目暂未公开")
	ErrProjectNoPermission  = errors.New("没有权限操作该项目")
	ErrUserBannedProject    = errors.New("已被封禁的用户不能管理项目")
	ErrNotPending           = errors.New("文章当前不在待审核状态")
	ErrInvalidAction        = errors.New("无效的审核操作")
	ErrNotPublishedArticle  = errors.New("只有已发布文章才可互动")
	ErrProjectNotPending    = errors.New("项目当前不在待审核状态")
	ErrRejectReasonRequired = errors.New("驳回时必须填写原因")
	ErrProjectContentEmpty  = errors.New("项目标题和正文不能为空")
	ErrUserBannedSubmit     = errors.New("已被封禁的用户不能提交文章")
	ErrUsernameExists       = errors.New("用户名已存在")
	ErrInvalidCredentials   = errors.New("用户名或密码错误")
	ErrAccountBanned        = errors.New("账号已被封禁")
	ErrUnsupportedTarget    = errors.New("不支持的内容类型")
	ErrNotificationNotFound = errors.New("通知不存在")

	ErrNoArticleIDs          = errors.New("no article ids provided")
	ErrDeleteNotDraft        = errors.New("only draft or rejected articles can be bulk deleted")
	ErrRejectReasonMissing   = errors.New("reject reason is required")
	ErrBulkNotPending        = errors.New("only pending articles can be bulk rejected")
	ErrBulkApproveNotPending = errors.New("only pending articles can be bulk approved")
	ErrNoProjectIDs          = errors.New("no project ids provided")
	ErrInvalidReviewAction   = errors.New("invalid review action")
	ErrProjectRejectReason   = errors.New("reject reason is required")
	ErrBulkProjectNotPending = errors.New("only pending projects can be bulk reviewed")
	ErrUploadNameEmpty       = errors.New("上传文件名不能为空")
	ErrUploadNameInvalid     = errors.New("上传文件名不合法")
	ErrUploadNotFound        = errors.New("上传文件不存在")
	ErrInvalidRole           = errors.New("无效的用户角色")
	ErrInvalidStatus         = errors.New("无效的用户状态")
	ErrLastAdminBan          = errors.New("不能封禁最后一个仍在启用的管理员")
	ErrLastAdminDelete       = errors.New("不能删除最后一个启用的管理员")
	ErrPublishedMetaOnly     = errors.New("only published projects can update meta")
	ErrSensitiveWordEmpty    = errors.New("敏感词不能为空")
	ErrSensitiveWordInvalid  = errors.New("敏感词不合法")
	ErrSensitiveWordExists   = errors.New("敏感词已存在")
	ErrBanThresholdRange     = errors.New("封禁阈值必须在 1 到 100 之间")
	ErrCommentEmpty          = errors.New("评论内容不能为空")
	ErrUserBannedComment     = errors.New("已被封禁的用户不能发表评论")
	ErrArticleNotPublished   = errors.New("未发布文章不能评论")
	ErrParentCommentNotFound = errors.New("父评论不存在")
	ErrInvalidReplyComment   = errors.New("回复的评论无效")
	ErrCategoryExists        = errors.New("分类已存在")
	ErrCategoryNameEmpty     = errors.New("分类名称不能为空")
	ErrCategoryNameLong      = errors.New("分类名称不能超过50个字符")
	ErrCategoryNameInvalid   = errors.New("分类名称无效")
	ErrTagNameEmpty          = errors.New("标签名称不能为空")
	ErrTagNameLong           = errors.New("标签名称不能超过30个字符")
	ErrTagExists             = errors.New("标签已存在")

	ErrCategoryNotFound = errors.New("分类不存在")
	ErrCategoryInUse    = errors.New("该分类下还有文章，无法删除")
	ErrTagNotFound      = errors.New("标签不存在")
	ErrTagInUse         = errors.New("该标签仍被文章使用，无法删除")
)
